logging.level:
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
spring:
  main:
    web-application-type: reactive
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/dvdrental"
    username: narif
    password: password